// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEEag_K2n0IlLXi_hq0dK1y2P5pozKyHM',
    appId: '1:32034997029:web:f889c06bfe3a512a7890cc',
    messagingSenderId: '32034997029',
    projectId: 'stock-vapes',
    authDomain: 'stock-vapes.firebaseapp.com',
    storageBucket: 'stock-vapes.appspot.com',
    measurementId: 'G-JP684YPRFG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY3eSSjFDb_JriGCfqYIkvblTYeWYsZwA',
    appId: '1:32034997029:android:64876c5608e911ab7890cc',
    messagingSenderId: '32034997029',
    projectId: 'stock-vapes',
    storageBucket: 'stock-vapes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDivd0X7xLdR6mg78ccyyf6Bhz7PrFuaOo',
    appId: '1:32034997029:ios:365738307ece57247890cc',
    messagingSenderId: '32034997029',
    projectId: 'stock-vapes',
    storageBucket: 'stock-vapes.appspot.com',
    iosClientId: '32034997029-l2ek66ohde9imk0i2lplmj4nqm40mf2u.apps.googleusercontent.com',
    iosBundleId: 'com.example.stockVapes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDivd0X7xLdR6mg78ccyyf6Bhz7PrFuaOo',
    appId: '1:32034997029:ios:365738307ece57247890cc',
    messagingSenderId: '32034997029',
    projectId: 'stock-vapes',
    storageBucket: 'stock-vapes.appspot.com',
    iosClientId: '32034997029-l2ek66ohde9imk0i2lplmj4nqm40mf2u.apps.googleusercontent.com',
    iosBundleId: 'com.example.stockVapes',
  );
}
